/**
 * Sanity Cache Management
 * 
 * CRITICAL: In production, ALL data comes from static cache files
 * No Sanity API calls should be made
 * 
 * Cache files are:
 * - Generated at build-time: scripts/cache-sanity-data.ts
 * - Stored in: public/sanity-cache/ (source)
 * - Deployed in: .next/static/sanity-cache/ (production)
 * - Served from: /_next/static/sanity-cache/ (HTTP)
 */

import { apiVersion, basePath, dataset, projectId } from './sanity.api'
import { getClient } from './sanity.client'

// Type for cache availability
export interface CacheStatus {
  available: boolean
  timestamp?: number
  source: 'cache' | 'api' | 'none'
  location?: string
}

// Production cache module - loaded at runtime from public/sanity-cache
let cacheModule: any = null
const CACHE_LOADED_AT = Date.now()

/**
 * Pre-load cache module on server startup
 * This ensures cache is available for all requests in production
 * 
 * CRITICAL: Cache files are imported from the build output
 * They are NOT bundled with the code, but served as static files
 */
export async function preloadCache(): Promise<boolean> {
  // Only preload in production
  if (process.env.NODE_ENV !== 'production') {
    console.info('[SANITY-CACHE] Development mode - using live API')
    return false
  }

  try {
    // Try to import the cache module
    // This will be generated by scripts/cache-sanity-data.ts
    // And served from .next/static/sanity-cache/index.json
    
    // In production, cache files are in public/sanity-cache (then copied to .next/static/)
    // We import from the built location
    const cache = require('../public/sanity-cache/index.json')
    
    if (!cache || typeof cache !== 'object') {
      console.warn('[SANITY-CACHE] Cache import failed - invalid format')
      return false
    }
    
    cacheModule = cache
    console.info('[SANITY-CACHE] ✅ Pre-loaded production cache from disk')
    console.info('[SANITY-CACHE] Cache location: .next/static/sanity-cache/')
    console.info('[SANITY-CACHE] Loaded from disk at:', new Date(CACHE_LOADED_AT).toISOString())
    return true
  } catch (error) {
    console.warn('[SANITY-CACHE] ⚠️ Cache module not available')
    console.warn('[SANITY-CACHE] Make sure to run: npm run build')
    console.warn('[SANITY-CACHE] Error:', error instanceof Error ? error.message : error)
    return false
  }
}

/**
 * Get cached data for a specific query
 * Matches query strings to their cache files
 * @param query - The GROQ query string
 * @returns Cached data or null if not found
 */
export function getCachedDataForQuery(query: string): any {
  if (!cacheModule) {
    console.warn('[SANITY-CACHE] Cache module not available')
    return null
  }

  const normalizedQuery = query.replace(/\s+/g, ' ').trim()

  // Map common queries to cache keys
  const queryMappings: Record<string, string> = {
    // Homepage
    'sharifHeroQuery': 'homepage',
    '_type == "hero"': 'homepage',
    '_type == "settings"': 'homepage',

    // Products
    '_type == "product"': 'allProducts',
    'product': 'allProducts',
    'productsListQuery': 'allProducts',
    'productDocBySlugQuery': 'allProducts',
    'productDocPaths': 'allProducts',

    // Categories
    '_type == "category"': 'categories',
    'categoriesQuery': 'categories',

    // Courses
    '_type == "course"': 'courses',
    'allCoursesQuery': 'courses',
    'courseBySlugQuery': 'courses',

    // Blog posts
    '_type == "post"': 'blogPosts',
    'blogListQuery': 'blogPosts',
    'postBySlugQuery': 'blogPosts',
    'allPostsQuery': 'blogPosts',

    // FAQs
    '_type == "faq"': 'faqs',
    'faqsByPageQuery': 'faqs',

    // Collections
    '_type == "collection"': 'collections',
    'allCollectionsQuery': 'collections',
    'collectionBySlugQuery': 'collections',
  }

  // Find matching cache key
  for (const [pattern, cacheKey] of Object.entries(queryMappings)) {
    if (normalizedQuery.includes(pattern)) {
      const cachedData = cacheModule[cacheKey]
      if (cachedData) {
        console.info(`[SANITY-CACHE] ✅ CACHE HIT: ${cacheKey}`)
        return cachedData
      }
    }
  }

  console.debug('[SANITY-CACHE] Query not mapped to cache')
  return null
}

/**
 * Get all cached data
 */
export function getAllCachedData(): any {
  return cacheModule || {}
}

/**
 * Get cache status for monitoring
 */
export function getCacheStatus(): CacheStatus {
  if (!cacheModule) {
    return {
      available: false,
      source: 'none',
    }
  }

  return {
    available: true,
    timestamp: CACHE_LOADED_AT,
    source: 'cache',
    location: '.next/static/sanity-cache/ (disk)',
  }
}

/**
 * Check if cache is available (for production builds)
 * 
 * CRITICAL: In production, this should ALWAYS be true
 * because cache is guaranteed to be in .next/static/sanity-cache/
 */
export function isCacheAvailable(): boolean {
  const available = cacheModule !== null && process.env.NODE_ENV === 'production'
  
  if (!available && process.env.NODE_ENV === 'production') {
    console.warn('[SANITY-CACHE] ⚠️ Cache not available in production!')
    console.warn('[SANITY-CACHE] Fallback to API - but performance will be degraded')
  }
  
  return available
}

/**
 * Force reload cache (for development)
 */
export async function reloadCache(): Promise<void> {
  // Clear require cache
  if (require.cache) {
    const keys = Object.keys(require.cache).filter(key => 
      key.includes('sanity-cache') || key.includes('public')
    )
    keys.forEach(key => delete require.cache[key])
  }
  await preloadCache()
}

/**
 * Get specific data from cache
 * @param dataType - Type of data (e.g., 'homepage', 'allProducts', etc.)
 */
export function getCachedData(dataType: string): any {
  if (!cacheModule) {
    console.warn(`[SANITY-CACHE] Cache not loaded - cannot get ${dataType}`)
    console.warn('[SANITY-CACHE] Make sure cache is in .next/static/sanity-cache/')
    return null
  }

  const data = cacheModule[dataType]

  if (!data) {
    console.warn(`[SANITY-CACHE] ⚠️ No cached data for: ${dataType}`)
    return null
  }

  console.info(`[SANITY-CACHE] ✅ Using cached data: ${dataType}`)
  return data
}

/**
 * Extract data from cache with fallback to API
 * This is the main method to use in server components
 * @param query - The GROQ query
 * @param params - Query parameters
 * @param options - Options for cache/API behavior
 */
export async function fetchWithCache(
  query: string,
  params?: Record<string, any>,
  options?: {
    bypassCache?: boolean
    forceApi?: boolean
  }
): Promise<any> {
  const isDraft = process.env.NEXT_PUBLIC_VERCEL_ENV === 'preview' || 
                   options?.forceApi === true

  // In draft/preview mode, always use API for live updates
  if (isDraft) {
    console.info('[SANITY-CACHE] Draft mode - using live API')
    const client = getClient()
    return client.fetch(query, params)
  }

  // Try cache first if available and not bypassed
  if (!options?.bypassCache && isCacheAvailable()) {
    const cachedData = getCachedDataForQuery(query)
    
    if (cachedData) {
      console.info('[SANITY-CACHE] Using cached data (NO API CALL)')
      return cachedData
    }
  }

  // Fallback to API
  console.info('[SANITY-CACHE] Cache miss, falling back to API')
  const client = getClient()
  return client.fetch(query, params)
}

// Initialize cache on module load (server-side only)
if (typeof window === 'undefined') {
  preloadCache().catch((error) => {
    console.warn('[SANITY-CACHE] Failed to preload cache:', error)
  })
}

